name: PDF Test

on:
  push:
    branches:
      - main

jobs:
  html_to_pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./index.html
          outputFile: ./output.pdf
          pdfOptions: '{"format": "A4"}'

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Upload PDF
          path: ./output.pdf
