name: PDF Test

on: [push]

jobs:
  html_to_pdf:
    name: HTML to PDF
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: html to pdf
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: ./example.html
          pdfFile: ./example.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: example.pdf
          path: ./example.pdf
