name: Create PDF

on:
  push:
    branches:
      - main

jobs:
  html_to_pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build:css

      - name: html to pdf
        uses: LukaszLapaj/html-to-pdf-action@master
        with:
          htmlFile: ./src/index.html
          outputFile: ./cv.pdf
          pdfOptions: '{"format": "A4"}'

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: Upload PDF
          path: ./cv.pdf

      - name: Get Current Date
        id: date
        run: echo "date=$(date +'%Y-%d-%m_%H.%M.%S')" >> $GITHUB_OUTPUT
      
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: releases/${{ steps.date.outputs.date }}
          files: ./cv.pdf
